Drivers:Touchscreen: Fix Goodix Complication
drivers/built-in.o: In function `gtp_hardwareinfo_set':
drivers/input/touchscreen/GT915L/gt9xx.c:2728: undefined reference to `tp_color'
drivers/input/touchscreen/GT915L/gt9xx.c:2728:(.text+0x3ec638): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against undefined symbol `tp_color'
drivers/input/touchscreen/GT915L/gt9xx.c:2728: undefined reference to `tp_color'
drivers/built-in.o: In function `gtp_read_lockdown_info':
drivers/input/touchscreen/GT915L/gt9xx.c:2708: undefined reference to `tp_color'
/drivers/input/touchscreen/GT915L/gt9xx.c:2708:(.text+0x3ec6ac): relocation truncated to fit: R_AARCH64_ADR_PREL_PG_HI21 against undefined symbol `tp_color'
drivers/input/touchscreen/GT915L/gt9xx.c:2708: undefined reference to `tp_color'
Makefile:963: recipe for target 'vmlinux' failed
make: *** [vmlinux] Error 1

* We Removed Tp_color from aw2013. so link it Panel_lnk instead of tp_color

Signed-off-by: muralivijay <muralidharan9845@gmail.com>